# Import Config
from .roles import ROLE_ADMIN, ROLE_STAFF, ROLE_SYSTEM_ADMIN, ROLE_TOTAL, ROLE_USER_ADMIN

# Administrator role groups.
SYSTEM_ADMIN_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_SYSTEM_ADMIN]
USER_ADMIN_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_USER_ADMIN]
GENERAL_ADMIN_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_ADMIN]

# Feature-specific aliases.
WARN_ROLES = USER_ADMIN_ROLES
BALANCER_ROLES = USER_ADMIN_ROLES
ADMIN_INFO_ROLES = USER_ADMIN_ROLES
CLEAR_ROLES = GENERAL_ADMIN_ROLES

# Non-admin feature permissions.
POST_END_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_SYSTEM_ADMIN]
