# Import Config
from .roles import ROLE_ADMIN, ROLE_STAFF, ROLE_SYSTEM_ADMIN, ROLE_TOTAL, ROLE_USER_ADMIN

# Role groups used for command authorization.

WARN_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_USER_ADMIN]
BALANCER_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_USER_ADMIN]
POST_END_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_SYSTEM_ADMIN]
CLEAR_ROLES = [ROLE_TOTAL, ROLE_STAFF, ROLE_SYSTEM_ADMIN]
ADMIN_INFO_ROLES = [ROLE_ADMIN]
